# Generated by Django 5.2.4 on 2025-09-02 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0016_alter_exit_trade_delete_flytrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DFly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('order_placed', 'Order Placed'), ('fills_received', 'Fills Received'), ('partial_fills_received', 'Partial Fills Received')], default='pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('order_placed_at', models.DateTimeField(blank=True, null=True)),
                ('fills_received_at', models.DateTimeField(blank=True, null=True)),
                ('close_requested_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('close_accepted', models.BooleanField(default=False)),
                ('ratio', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_lots', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dfly', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DFlyExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_exit_lots', models.PositiveIntegerField(help_text='Number of lots requested to be closed in this exit event.')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, help_text='The price at which the exit was executed.', max_digits=10, null=True)),
                ('received_lots', models.PositiveIntegerField(default=0, help_text='Number of lots actually closed in this exit event.')),
                ('exit_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('order_placed', 'Exit Order Placed'), ('filled', 'Completely Filled'), ('partial_filled', 'Partially Filled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of this exit request.', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When this exit request was created.')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this exit request was approved.', null=True)),
                ('order_placed_at', models.DateTimeField(blank=True, help_text='When the exit order was placed with the broker.', null=True)),
                ('filled_at', models.DateTimeField(blank=True, help_text='When the exit was considered filled.', null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated Profit/Loss for the lots closed in this event.', max_digits=10, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='When all the lots are received.')),
                ('dfly', models.ForeignKey(help_text='The DFly instance associated with this exit event.', on_delete=django.db.models.deletion.CASCADE, related_name='exit_events', to='flytrade.dfly')),
                ('exit_approved_by', models.ForeignKey(blank=True, help_text='Manager who approved this exit request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfly_exit_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('exit_initiated_by', models.ForeignKey(help_text='User who initiated this exit request.', on_delete=django.db.models.deletion.CASCADE, related_name='dfly_exit_requests_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DFly Exit',
                'verbose_name_plural': 'DFly Exits',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lots_and_price', models.JSONField(default=list)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legname', to='trade.availability')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread_type', models.CharField(choices=[('fly', 'Fly Spread'), ('custom', 'Custom'), ('dfly', 'Part of DFly')], max_length=15)),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('order_placed', 'Order Placed'), ('fills_received', 'Fills Received'), ('partial_fills_received', 'Partial Fills Received')], default='pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('order_placed_at', models.DateTimeField(blank=True, null=True)),
                ('fills_received_at', models.DateTimeField(blank=True, null=True)),
                ('close_requested_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('close_accepted', models.BooleanField(default=False)),
                ('ratio', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_lots', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_spreads', to=settings.AUTH_USER_MODEL)),
                ('legs', models.ManyToManyField(related_name='legs_of_spread', to='flytrade.leg')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dfly',
            name='spreads',
            field=models.ManyToManyField(to='flytrade.spreads'),
        ),
        migrations.CreateModel(
            name='SpreadsExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_exit_lots', models.PositiveIntegerField(help_text='Number of lots requested to be closed in this exit event.')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, help_text='The price at which the exit was executed.', max_digits=10, null=True)),
                ('received_lots', models.PositiveIntegerField(default=0, help_text='Number of lots actually closed in this exit event.')),
                ('exit_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('order_placed', 'Exit Order Placed'), ('filled', 'Completely Filled'), ('partial_filled', 'Partially Filled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of this exit request.', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When this exit request was created.')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this exit request was approved.', null=True)),
                ('order_placed_at', models.DateTimeField(blank=True, help_text='When the exit order was placed with the broker.', null=True)),
                ('filled_at', models.DateTimeField(blank=True, help_text='When the exit was considered filled.', null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated Profit/Loss for the lots closed in this event.', max_digits=10, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='When all the lots are received.')),
                ('exit_approved_by', models.ForeignKey(blank=True, help_text='Manager who approved this exit request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spreads_exit_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('exit_initiated_by', models.ForeignKey(help_text='User who initiated this exit request.', on_delete=django.db.models.deletion.CASCADE, related_name='spreads_exit_requests_initiated', to=settings.AUTH_USER_MODEL)),
                ('spread', models.ForeignKey(help_text='The spread associated with this exit event.', on_delete=django.db.models.deletion.CASCADE, related_name='exit_events', to='flytrade.spreads')),
            ],
            options={
                'verbose_name': 'Spreads Exit',
                'verbose_name_plural': 'Spreads Exits',
                'ordering': ['-requested_at'],
            },
        ),
    ]
