# Generated by Django 5.2.4 on 2025-07-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('start_month', models.CharField(max_length=3)),
                ('end_month', models.CharField(max_length=3)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trade.availability'),
        ),
        migrations.AddField(
            model_name='availability',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.commodity'),
        ),
        migrations.AddField(
            model_name='availability',
            name='contract_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.contractmonth'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('contract_month', 'commodity')},
        ),
    ]
