# Generated by Django 5.2.4 on 2025-07-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_availability_commodity_contractmonth_trade_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='note',
        ),
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
