# Generated by Django 5.2.4 on 2025-07-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_remove_trade_note_alter_trade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trade.availability'),
        ),
    ]
