# Generated by Django 5.2.4 on 2025-07-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_trade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
