# Generated by Django 5.2.4 on 2025-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_trade_close_requested_at_trade_fills_received_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='close_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
