# Generated by Django 5.2.4 on 2025-07-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_trade_close_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='settlement_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
