# Generated by Django 5.2.4 on 2025-07-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_trade_profit_trade_settlement_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='settlement_price',
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booked_lots', models.PositiveIntegerField()),
                ('unbooked_lots', models.PositiveIntegerField()),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('settlement_price_unbooked', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='trade.trade')),
            ],
        ),
    ]
