# Generated by Django 5.2.4 on 2025-07-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_remove_trade_profit_remove_trade_settlement_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('order_placed', 'Order Placed'), ('fills_received', 'Fills Received'), ('partial_fills_received', 'Partial Fills Received')], default='pending', max_length=25),
        ),
    ]
