# Generated by Django 5.2.4 on 2025-07-23 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_alter_profit_updated_at_alter_trade_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_exit_lots', models.PositiveIntegerField(help_text='Number of lots requested to be closed in this exit event.')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, help_text='The price at which the exit was executed.', max_digits=10, null=True)),
                ('recieved_lots', models.PositiveIntegerField(default=0, help_text='Number of lots actually closed in this exit event.')),
                ('exit_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('order_placed', 'Exit Order Placed'), ('filled', 'Completely Filled'), ('partial_filled', 'Partially Filled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of this exit request.', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When this exit request was created.')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this exit request was approved.', null=True)),
                ('order_placed_at', models.DateTimeField(blank=True, help_text='When the exit order was placed with the broker.', null=True)),
                ('filled_at', models.DateTimeField(blank=True, help_text='When the exit was considered filled.', null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated Profit/Loss for the lots closed in this event.', max_digits=10, null=True)),
                ('exit_approved_by', models.ForeignKey(blank=True, help_text='Manager who approved this exit request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('exit_initiated_by', models.ForeignKey(help_text='User who initiated this exit request.', on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests_initiated', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(help_text='The trade associated with this exit event.', on_delete=django.db.models.deletion.CASCADE, related_name='exit_events', to='trade.trade')),
            ],
            options={
                'verbose_name': 'Trade Exit',
                'verbose_name_plural': 'Trade Exits',
                'ordering': ['-requested_at'],
            },
        ),
    ]
