# Generated by Django 5.2.4 on 2025-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='When all the lots are receieved.'),
        ),
    ]
