# Generated by Django 5.2.4 on 2025-08-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_exit_is_closed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='settlement_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='trade.commodity')),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='end_month',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='trade.settlement'),
        ),
        migrations.AddField(
            model_name='availability',
            name='start_month',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='trade.settlement'),
        ),
        migrations.RemoveField(
            model_name='availability',
            name='contract_month',
        ),
    ]
