# Generated by Django 5.2.4 on 2025-08-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractMonth',
        ),
        migrations.DeleteModel(
            name='Profit',
        ),
    ]
