# Generated by Django 5.2.4 on 2025-08-18 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_delete_contractmonth_delete_profit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='fills_received_of',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='fills_recivied_for',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='lots',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='stop_loss',
        ),
        migrations.AddField(
            model_name='trade',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='lots_and_price',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trade',
            name='total_lots',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FlyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lots', models.PositiveIntegerField()),
                ('trade_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('lots_leg1', models.PositiveIntegerField()),
                ('lots_leg2', models.PositiveIntegerField()),
                ('price_leg1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_leg2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss_leg1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_loss_leg2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ratio', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('order_placed', 'Order Placed'), ('fills_received', 'Fills Received'), ('partial_fills_received', 'Partial Fills Received')], default='pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('order_placed_at', models.DateTimeField(blank=True, null=True)),
                ('fills_received_at', models.DateTimeField(blank=True, null=True)),
                ('close_requested_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('close_accepted', models.BooleanField(default=False)),
                ('fills_recivied_for_leg1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fills_recivied_for_leg2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_trades_flytrade', to=settings.AUTH_USER_MODEL)),
                ('leg1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_trade_leg1', to='trade.availability')),
                ('leg2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_trade_leg2', to='trade.availability')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
