# Generated by Django 5.2.4 on 2025-09-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_remove_trade_fills_received_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='trade',
            field=models.ForeignKey(help_text='The trade associated with this exit event.', on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='trade.trade'),
        ),
        migrations.DeleteModel(
            name='FlyTrade',
        ),
    ]
